### ISSUE TITLE
how make

### ISSUE THREAD

**Issue by Wolf65** [sonoro1234/LuaJIT-ImGui#11]
I understand that I ask, perhaps a stupid question. but how to collect the contents of the archive from the LuaJIT binding to imgui 1.62 imgui_release.rar only for version 1.71

**Comment by sonoro1234** [comment]
It is not stupid.
You cant, it has to be recompiled from the repo.
If you only build this directory you will get imgui_glfw or imgui_sdl (depending on you choice)
but not glfw or luajit,

In another repo of mine https://github.com/sonoro1234/anima you will get all three if you compile it, but also some stuff in which perhaps you are not interested

**Comment by sonoro1234** [comment]
Do not doubt in making any question relative to compiling: It would help others to get guidance

**Comment by Wolf65** [comment]
Thank you all turned out
there were only a few dirty tricks.
After `git clone --recursive` the luajit-async / pthread folder did not incline it was necessary to manually make a pthread clone.
And so it turned out all just
1) in the anima folder
1.1) you do not need to disable the CMakeLists file (my settings 

```
option (ANIMA_BUILD_LUAJIT" Build LuaJIT "ON)
option (ANIMA_BUILD_IM "Build im" OFF)
option (ANIMA_BUILD_GLFW "Build LuaJIT-GLFW" ON)
option (ANIMA_BUILD_SDL "Build LuaJIT-SDL2" OFF)
option (ANIMA_BUILD_IMGUI "Build LuaJIT-IMGUI" ON)
option (ANIMA_BUILD_SNDFILE "Build LuaJIT-libsndfile" OFF)
option (ANIMA_BUILD_RTAUDIO "Build LuaJIT-rtaudio" OFF) 
```)
2) `cmake -G "MinGW Makefiles" -DLUAJIT_BIN = "C: \ LuaJIT-ImGui"` in the anima folder
3) `mingw32-make install`
maybe someone needs a sequence

**Comment by sonoro1234** [comment]
Set the options in step 2:
```
cmake -G "MinGW Makefiles" -DLUAJIT_BIN = "C: \ LuaJIT-ImGui" -DANIMA_BUILD_IM=off
```
So that repo files dont need to be touched

**Comment by sonoro1234** [comment]
Just changed pthread to my fork and submodule is updated correctly.
Thanks for reporting.
