### ISSUE TITLE
What's the license?

### ISSUE THREAD

**Issue by HankiDesign** [sonoro1234/LuaJIT-ImGui#14]
Great job with the project!

Which license are you using to release this library? I'm listing it on [Awesome dear imgui](https://github.com/HankiDesign/awesome-dear-imgui) but it would be helpful to know the license as well. Thanks!

**Comment by sonoro1234** [comment]
I guess it should be the same as ImGui

**Comment by HankiDesign** [comment]
Could you add the license to the repository, so that I can refer to it directly? Then it would also be legally clear for anyone else using the project. It would be much appreciated!

**Comment by sonoro1234** [comment]
Done!!

**Comment by HankiDesign** [comment]
Great thanks, I updated the list to include the license.
