### ISSUE TITLE
Using InputText with callback throws error

### ISSUE THREAD

**Issue by tversteeg** [sonoro1234/LuaJIT-ImGui#15]
When I use the following code I get `too many callbacks` as an error after a while:

```lua
lib.igInputText("##input", "test", 1024, ig.lib.ImGuiInputTextFlags_CallbackCompletion, function()
	print("Hi")
	return 0
end, nil)
```

What is the proper way to pass callbacks to `InputText`?

**Comment by sonoro1234** [comment]
First create a callback as
```Lua
local cbt = ffi.cast("ImGuiInputTextCallback",function(aa)
	print("Hi",aa)
	return 0
end)
```
and use cbt as callback. If not doing this you create a new callback each time

**Comment by tversteeg** [comment]
Thanks for the quick reply.

When I do this I get a `bad callback` error.

**Comment by sonoro1234** [comment]
look for `bad callback` at http://luajit.org/ext_ffi_semantics.html

may be you need to use jit.off (not in my test)

**Comment by tversteeg** [comment]
Turning of `jit.off()` seems to work, what I also found out in the meantime is that the following also works:
```lua
ffi.cast("int (__stdcall *)(ImGuiInputTextCallbackData*)", ..
```

**Comment by sonoro1234** [comment]
solved
