### ISSUE TITLE
cannot resolve symbol 'resizeSolidOf'

### ISSUE THREAD

**Issue by MGeymer** [sonoro1234/LuaJIT-ImGui#21]
branch anima - master
love 11.3
commit f69b3cf

This time I needed to build for windows, maybe I did something wrong but the "make install" didn't work for me, I guess that's because I have msvc, so I did the build via VS, here's the dll problem when I run.
[cimgui_sdl.zip](https://github.com/sonoro1234/LuaJIT-ImGui/files/5168757/cimgui_sdl.zip)
![изображение](https://user-images.githubusercontent.com/20752579/92119780-b1057100-ee11-11ea-86c1-20f7aeb55bb7.png)

**Comment by sonoro1234** [comment]
Did you compiled with `-DIMPL_EXTRAS=yes` ?

**Comment by MGeymer** [comment]
Yes, it is, I attached the dll that I got, suddenly it's about him. I compiled as usual.
```cmake -DLUAJIT_BIN="/home/user/anima" ../anima```
Then I got the VS project files. I opened and compiled, put the DLL in the LOVE2D directory and that's it.
About ```DIMPL_EXTRAS=yes``` I don't know, I didn't change anything in the settings except that I turned off glfw.

**Comment by sonoro1234** [comment]
Ok, so you are compiling with anima repo but `resizeSolidOf` is not in the LuaJIT-ImGui version that goes with anima.
May be you pulled from LuaJIT-ImGui directly so repos are mixed.

Delete your anima repository, do a fresh new clone of anima and then recompile,

**Comment by sonoro1234** [comment]
> This time I needed to build for windows, maybe I did something wrong but the "make install" didn't work for me

for MSVC
after opening a window with
"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars32.bat"
(or similar according to your instalation)

cmake -G"NMake Makefiles" -DLUAJIT_BIN="c:/anima32msvc" ../../anima
nmake install (or `cmake --build . --target install` which work for all compilers)

if you dont want to use nmake but visual studio you could generate with

-G"Visual Studio 15 2017 Win64" but for all alternatives take a look at https://cmake.org/cmake/help/latest/manual/cmake-generators.7.html

**Comment by sonoro1234** [comment]
Any updates on this issue?

**Comment by MGeymer** [comment]
I think not, I made an assembly of an earlier version on which I did in linux.
