### ISSUE TITLE
64-bit integers in cimgui+lua api?

### ISSUE THREAD

**Issue by ocornut** [sonoro1234/LuaJIT-ImGui#23]
Hello,

I've been considering changing some of the low-level flags, e.g. think `ImGuiWindowFlags`, `ImGuiTableFlags` etc. to use 64-bit integers down the line. 

Do you think that would cause issues with
- cimgui 
- luajit-imgui
- other lua wrappers based on cimgui
?

Thank you!

**Comment by sonoro1234** [comment]
Not completely sure until we try. But I think that if type is int64_t it will remain the same size whether compilation is 32bits or 64bits, so I would not expect any problem. (I would avoid the ambiguity of `long` or `long long`)

**Comment by ocornut** [comment]
Thanks for looking into this.
I didn't notice the full edited answer until now as I just pushed a test branch for you to try:

https://github.com/ocornut/imgui/tree/features/test_64bit_flags

I'm not totally sure how enums works in C, but the values could easily be replaced by `#define` or static const values.

> print(ffi.C.uno, ffi.C.UNO, ffi.C.DOS)

Is there a possibility that it's a `print()` problem, but somehow the correct value could get passed correctly to the an underlying C function?

**Comment by ocornut** [comment]
Some extra references
https://luajit.org/ext_ffi_semantics.html

**Comment by sonoro1234** [comment]
> Is there a possibility that it's a `print()` problem, but somehow the correct value could get passed correctly to the an underlying C function?

No, ffi.C.UNO is converted to Lua number before printing.

> I'm not totally sure how enums works in C, but if required on C-side, the values could be replaced by `#define` or static const values.

This was the recomendation in https://stackoverflow.com/questions/41954767/c-enum-with-32-bit-values.
LuaJIT is not able to handle static const int64_t (only static const int32_t ) so they will have to be binded as Lua numbers (with loss of precission or generate cdata for uint64_t as `2ULL^63`)

**Comment by sonoro1234** [comment]
> https://github.com/ocornut/imgui/tree/features/test_64bit_flags

Apart from 1<<60 the biggest one is 1<<28 so I guess that you need even more flags that will be added later?

**Comment by ocornut** [comment]
Yes 32 bits limit is causing issues with the api design, docking has more, and Tables already have as many flags as windows and i’m considering changing some Tables api entirely to avoid running out of flags, hence my wonder to find if 64 bits flags is something we could use.

**Comment by sonoro1234** [comment]
> https://github.com/ocornut/imgui/tree/features/test_64bit_flags

Did some C tests with:

cimgui.h
```C
enum ImGuiWindowFlags_ //: ImS64
{
    ImGuiWindowFlags_None = 0,
    ImGuiWindowFlags_NoTitleBar = 1LL << 60,
```

cimgui_test: main.c
```C
printf("%llu size: %u\n",ImGuiWindowFlags_NoTitleBar,sizeof(ImGuiWindowFlags_NoTitleBar));
```

- mingw-w64 32 bits
`1152921504606846976 size: 8`

- nmake 32 bits (very strange sizeof)
`17179869184 size: 6765976`

- nmake 64 bits
`0 size: 4`

So that only mingw-w64 32bits is succeding

**Comment by ocornut** [comment]
> very strange sizeof

I think it is because 64-bit values in printf are not standard so it's pulling 32-bits, and then next value pulled from wrong location of the stack, supposed to use `%"PRId64"` as a format value (it's ugly). Or if you make it 2 calls to printf() the second will be guaranteed good as least.

**Comment by sonoro1234** [comment]
The only way to succed on all compilers is:

```C
static const ImS64 ImGuiWindowFlags_NoTitleBar = 1LL << 60;

static const ImS64 ImGuiWindowFlags_NoDecoration = (1LL << 60) | ImGuiWindowFlags_NoResize | ImGuiWindowFlags_NoScrollbar | ImGuiWindowFlags_NoCollapse;

//static const ImS64 ImGuiWindowFlags_NoDecoration = ImGuiWindowFlags_NoTitleBar | ImGuiWindowFlags_NoResize | ImGuiWindowFlags_NoScrollbar | ImGuiWindowFlags_NoCollapse;
```

The third declaration refuses to compile in nmake with:
` el inicializador no es una constante` (the initializer is not a constant) which I found strange just being declared as static const.

**Comment by sonoro1234** [comment]
Just pushed to cimgui for 64-bits enums and imgui_tables.cpp addition.
LuaJIT-ImGui will need more changes.

Are 64-bits enums and tables going to be added in v1.80?

**Comment by ocornut** [comment]
Tables are going to be added in 1.80, hopefully tagged next week.

64-bits flags, it depends if we can guarantee they won't break non-C++ languages....
64-bits flags are less urgent but I may alter some tables API depending on whether I have visibility of if they are possible. If I'm not sure they are possible I may prefer to change Tables API into a less elegant but more future proof way.

**Comment by sonoro1234** [comment]
> 64-bits flags, it depends if we can guarantee they won't break non-C++ languages....

So perhaps we should ask about the proposed solution in cimgui?

**Comment by ocornut** [comment]
Yes, right!

**Comment by ocornut** [comment]
Bgfx Lua bindings uses custom format strings:
https://github.com/cloudwu/lua-bgfx/blob/37ae5c7389a7e48e7cc2bf9a03804edbee054a13/luabgfx.c#L3510
Which I think works well for this very specific finite case of options which happens to have a nice mapping to letter but wouldn't work for dear imgui options, they are so specific and specialized.

I mentioned Javascript and Lua and someone on Twitter mentioned that 53-bits flags should be ok in those languages.
The practice use case is to be OR-ing many of those flags and pass a single 64-bits value to the C/C++ code.
If we can reliably access up to 53-bits that already an extra 21-bits we
 can make use of :)

**Comment by sonoro1234** [comment]
> I mentioned Javascript and Lua and someone on Twitter mentioned that 53-bits flags should be ok in those languages.

It is a 52 bits limit for converting from uint64_t to Lua number (a double) without loss of precission. But there is also `1ULL` notation to mean not a Lua number but an uint64_t without any loss.

**Comment by sonoro1234** [comment]
```Lua
local a = 2ULL^53-1
print(a)
print(string.format("%u",tonumber(a)))
```
prints 
9007199254740991ULL
9007199254740991

But
```Lua
local a = 2ULL^54-1
print(a)
print(string.format("%u",tonumber(a)))
```
prints
18014398509481983ULL
18014398509481984

**Comment by sonoro1234** [comment]
Done in cimgui and here
