### ISSUE TITLE
Compilling with SDL in Windows for Love

### ISSUE THREAD

**Issue by Hperigo** [sonoro1234/LuaJIT-ImGui#25]
Hello, I'm trying to compile LuaJIT-ImGui to use with Love2d and I ran to a problem when trying to compile it.

I did manage to compile LuaJit-SDL2 but when I run the following command from a folder inside LuaJIT-ImGui folder I get an `SDL_INCLUDE-NOTFOUND` error 

`cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DIMPL_GLFW=no -DSDL_PATH="C:\Users\Henrique\Documents\dev\lua\LuaJIT-SDL2\SDL" -DLUAJIT_BIN="C:\Users\Henrique\Documents\dev\lua\luajit\src" ..`

here's the full error: 
```
-- Building for: Visual Studio 16 2019
-- The C compiler identification is MSVC 19.28.29913.0
-- The CXX compiler identification is MSVC 19.28.29913.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29910/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29910/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Deprecation Warning at CMakeLists.txt:2 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- SDL_PATH defined as C:\Users\Henrique\Documents\dev\lua\LuaJIT-SDL2\SDL
CMake Error at C:/Users/Henrique/Documents/dev/lua/LuaJIT-SDL2/SDL/SDL2Config.cmake:1 (include):
  include could not find requested file:

    C:/Users/Henrique/Documents/dev/lua/LuaJIT-SDL2/SDL/SDL2Targets.cmake
Call Stack (most recent call first):
  CMakeLists.txt:133 (FIND_PACKAGE)


-- sdlfound
CMake Warning (dev) at CMakeLists.txt:135 (get_target_property):
  Policy CMP0045 is not set: Error on non-existent target in
  get_target_property.  Run "cmake --help-policy CMP0045" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  get_target_property() called with non-existent target "SDL2::SDL2".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- sdlinclude is SDL_INCLUDE-NOTFOUND or
-- sdlinclude2 is
-- Configuring incomplete, errors occurred!
See also "C:/Users/Henrique/Documents/dev/lua/LuaJIT-ImGui/build/CMakeFiles/CMakeOutput.log".
```

any help is appreciated!

**Comment by sonoro1234** [comment]
There is not such thing as compiling for Love, you just need to compile for SDL to be able to run with Love. (only installation must be adapted for love)

You dont need LuaJIT-SDL2 to compile, just SDL2 https://github.com/libsdl-org/SDL , SDL2 should be compiled and installed so that `SDL_PATH` points to where it is installed. (or -DSDL_PATH="" to let cmake find it)

`LUAJIT_BIN` should point to where `cimgui_sdl` is going to be installed (not to luajit src which is not needed) In your use case it should be love folder.

Also: You can download from https://github.com/sonoro1234/anima/releases/tag/v0.2b in order to avoid compiling. Take `cimgui_sdl.dll` and also imgui folder to love folder in order to have a love installation.

**Comment by Hperigo** [comment]
Hi, thank you for the quick reply =) 

I ended up following your suggestion of downloading `cimgui_sdl` from anima and dropping it next to the love executable. It worked great!
