### ISSUE TITLE
Implementation with SDL and DirectX

### ISSUE THREAD

**Issue by ElectricSquid** [sonoro1234/LuaJIT-ImGui#29]
Is there perhaps any chance I could get some guidance on how to make this work with DirectX9? I got the `LuaJIT-Window` release from [anima](https://github.com/sonoro1234/anima), and have been trying to understand how everything works. So far I've tried creating the implementation functions in `sdl.lua`, defining them in `cdefs.lua`, and then modifying `minimal_sdl.lua` to use the new implementation. After doing so I was met with the following error, where I've been stuck since:

```
luajit.exe: ...LuaJIT-Window-0.2b-Win32\LuaJIT-Window\lua\imgui\sdl.lua:317: cannot resolve symbol 'ImGui_ImplDX9_Init': The specified procedure could not be found.

stack traceback:
        [C]: in function '__index'
        ...LuaJIT-Window-0.2b-Win32\LuaJIT-Window\lua\imgui\sdl.lua:317: in function 'Init'
        examples/LuaJIT-ImGui/examples/minimal_sdl_dx9.lua:34: in main chunk
        [C]: at 0x00402d26
```

I'm wagering that I would need to integrate the new DX9 implementation calls into `cimgui_sdl.dll` but I am lost how I would go about doing that. Is my current approach appropriate or do I need to go about this in a different way? If I'm on the correct path, how do I integrate the new implementations into `cimgui_sdl`?

Here's the additions to `sdl.lua` and `cdefs.lua` respectively for reference:
``` lua
-- sdl.lua
-- Code placed right after M.Imgui_Impl_glfw_opengl2 = setmetatable({},Imgui_Impl_glfw_opengl2)

local Imgui_Impl_SDL_DX9 = {}
Imgui_Impl_SDL_DX9.__index = Imgui_Impl_SDL_DX9

function Imgui_Impl_SDL_DX9.__call()
    return setmetatable({ctx = lib.igCreateContext(nil)},Imgui_Impl_SDL_DX9)
end

function Imgui_Impl_SDL_DX9:Init(window, device)
    --self.window = window
    lib.ImGui_ImplSDL2_InitForD3D(window);
    lib.ImGui_ImplDX9_Init(device);
end

function Imgui_Impl_SDL_DX9:Destroy()
    lib.ImGui_ImplDX9_Shutdown();
    lib.ImGui_ImplSDL2_Shutdown();
    lib.igDestroyContext(self.ctx);
end

function Imgui_Impl_SDL_DX9:NewFrame()
    lib.ImGui_ImplDX9_NewFrame();
    lib.ImGui_ImplSDL2_NewFrame();
    lib.igNewFrame();
end

function Imgui_Impl_SDL_DX9:Render()
    lib.igRender()
    lib.ImGui_ImplDX9_RenderDrawData(lib.igGetDrawData());
end
M.Imgui_Impl_SDL_DX9 = setmetatable({},Imgui_Impl_SDL_DX9)

```
``` lua
-- cdefs.lua
cdecl = cdecl .. [[
 -- Already included code here...
 bool ImGui_ImplDX9_Init(IDirect3DDevice9* device);
 void ImGui_ImplDX9_Shutdown();
 void ImGui_ImplDX9_NewFrame();
 void ImGui_ImplDX9_RenderDrawData(ImDrawData* draw_data);
]]
```
Thank you for your time, and great work on making this binding, I see how much work you've put into this.

**Comment by sonoro1234** [comment]
Imgui_impl_dx9.cpp must be compiled for that

**Comment by ElectricSquid** [comment]
Thanks for your response! I'm closing this because I feel I'm in way over my head in my current knowledge to work out what needs to be done for my given objective.

**Comment by sonoro1234** [comment]
I could made a branch just to test directX but, why directX instead of opengl? and why dx9 but not dx12?

**Comment by ElectricSquid** [comment]
My goal was to implement imgui into a mod for Payday 2 as I've grown to love the interface and its api. Payday 2 uses LuaJIT for its code, and DirectX9 for its rendering. However, the documentation in the Payday 2 modding scene is extremely sparse so I've been trying to piece things together over the last two weeks. 

My understanding was that if I could get the dx9 implementation into lua then I would be able to get the gui working in the mod. Currently my knowledge of working with compilers is rather thin so I'm a bit lost in all of the compilation instructions and what work is involved with getting the `imgui_impl_dx9.cpp` to compile into lua. Additionally, there are some key methods in the payday 2 engine that are unknown in how they function so I'm not quite sure if I would be able to get it working in game even if I could compile the dx9 implementation. 

I am however still down to try getting it to compile for the sake of learning and possibly creating some documentation for future users trying to port renderers.
