### ISSUE TITLE
Creating several windows in one interpirator

### ISSUE THREAD

**Issue by Sparebola** [sonoro1234/LuaJIT-ImGui#32]
Hi. I need to load several scripts into one Luajit interpreter. There is a problem: windows does not work.
I use ready-made binary files from release v0.2b anima [LuaJIT-Window-0.2b-Win32.zip](https://github.com/sonoro1234/anima/releases/download/v0.2b/LuaJIT-Window-0.2b-Win32.zip)
When running the two scripts LuaJIT-Window\examples\minimal_main.lua error: [Picture](https://i.imgur.com/29DA9ub.jpg)
When running one minimal_main all is fine: [Picture](https://i.imgur.com/jg6OIZ5.jpg)
This doesn't work on SDL and on GLFW.
I also tried to implement a wrap that would create a window when it was absent and return it when it was present:
```
local ffi = require "ffi"
local sdl = require "sdl2_ffi"

ffi.cdef [[
typedef struct SDL_Window SDL_Window;
SDL_Window *SDL_GL_GetCurrentWindow(void);
void* SDL_GL_GetCurrentContext(void);
int SDL_GL_MakeCurrent(SDL_Window* window,void* context);
]]

local function createWindow()
    local openWindow = sdl.SDL_GL_GetCurrentWindow()
    if openWindow == nil then
        if (sdl.init(sdl.INIT_VIDEO + sdl.INIT_TIMER) ~= 0) then
            print(string.format("Error: %s\n", sdl.getError()));
            return -1;
        end
    
        sdl.gL_SetAttribute(sdl.GL_CONTEXT_FLAGS, sdl.GL_CONTEXT_FORWARD_COMPATIBLE_FLAG);
        sdl.gL_SetAttribute(sdl.GL_CONTEXT_PROFILE_MASK, sdl.GL_CONTEXT_PROFILE_CORE);
        sdl.gL_SetAttribute(sdl.GL_DOUBLEBUFFER, 1);
        sdl.gL_SetAttribute(sdl.GL_DEPTH_SIZE, 24);
        sdl.gL_SetAttribute(sdl.GL_STENCIL_SIZE, 8);
        sdl.gL_SetAttribute(sdl.GL_CONTEXT_MAJOR_VERSION, 3);
        sdl.gL_SetAttribute(sdl.GL_CONTEXT_MINOR_VERSION, 2);
        local current = ffi.new("SDL_DisplayMode[1]")
        sdl.getCurrentDisplayMode(0, current);
        local window = sdl.createWindow("ImGui SDL2+OpenGL3 example", sdl.WINDOWPOS_CENTERED, sdl.WINDOWPOS_CENTERED, 700,
            500,
            sdl.WINDOW_OPENGL + sdl.WINDOW_RESIZABLE);
        local gl_context = sdl.gL_CreateContext(window);
        return window, gl_context
    end
    return openWindow, sdl.SDL_GL_GetCurrentContext()
end

return createWindow
```
With this approach, I can't get the context right. One window does start to draw imgui from different scripts, but every tick the picture blinks
I can afford to create one window, for multiple scripts, since I use Viewports, so it's even for the best.
Please advise how to fix the bug with windows hanging (like in the first option with minimal_main) or losing context through the wrapper.

**Comment by sonoro1234** [comment]
I am not sure to understand. Do you mean creating two sdl (or glfw) windows?

**Comment by Sparebola** [comment]
Yes, I want to create two windows, or one that will render imgui from two scripts.

**Comment by sonoro1234** [comment]
For the first , search multi-context in imgui repo. For the second each script should return a function to be runned in the drawing loop of main script.

**Comment by Sparebola** [comment]
The first option I will try with the multi-context, but the second will not work, because the scripts are isolated from each other (each has its own global scope)

**Comment by sonoro1234** [comment]
> but the second will not work, because the scripts are isolated from each other (each has its own global scope)

supose you have:

```Lua
--script1.lua
local ig = require"imgui.glfw"

local function script1draw()
	if ig.Begin"script1 window" then
		if ig.Button"Hellosc1" then
			print"Hello World!! from sc1"
		end
	end
	ig.End()
end

return script1draw
```

then you could add line `local sdraw1 = require"script1"` to https://github.com/sonoro1234/LuaJIT-ImGui/blob/docking_inter/examples/minimal_main.lua#L26

and afterwards add line `sdraw1()` to https://github.com/sonoro1234/LuaJIT-ImGui/blob/docking_inter/examples/minimal_main.lua#L40

**Comment by sonoro1234** [comment]
You could even get rid of `local ig = require"imgui.glfw"` in script1.lua (useful if you dont know if it is glfw or sdl) by passing `ig` as an argument to `script1draw(ig)` and calling `sdraw1(ig)`

Or using `imgui.window` you could call sdraw1(ig) after https://github.com/sonoro1234/LuaJIT-ImGui/blob/docking_inter/examples/implot_sample.lua#L41

**Comment by Sparebola** [comment]
Again. Scripts can't load themselves, let me tell you how it works.
Luajit runs all lua from a specific folder. These lua scripts are completely independent and should not interact with each other in any way. They can only use shared libraries. That's why in my first post I did a check for the existence of an SDL window and, if it already exists, return it.
If you are wondering how lua scripts are loaded in LuaJIT, I use [RakSamp](https://www.blast.hk/threads/108052/) , but it doesn't affect the interpreter in any way, there is no Draw API

**Comment by Sparebola** [comment]
There can also be any number of scripts. The library cannot know how many

**Comment by sonoro1234** [comment]
I am afraid that I cant help you with RakSamp as I dont know it. My only help will be the snippet above where you load one script from another one.

**Comment by Sparebola** [comment]
I will send you an example with the usual LuaJIT interpreter later, where the two examples from the first post will be implemented.
RakSamp is only here to run lua scripts, providing an API not related to window or drawing
I didn't mean to confuse you with this

**Comment by Sparebola** [comment]
I made three examples. You can quickly run through a bat file in the "run" folder:

1. glfwMinimalDouble - launches two windows via glfw
2. sdlMinimalDouble - launches two windows via sdl
3. sdlOneWindow - runs a single window, in which draws two scripts at once

Errors:

- Method 1 and 2 - window freeze
- Method  3 - blinking imgui

LuaJIT and binary files are taken from anima release
[project.zip](https://github.com/sonoro1234/LuaJIT-ImGui/files/10786916/project.zip)

**Comment by sonoro1234** [comment]
I have runned with binaries compiled for debug to get assertions:

```
C:\LuaGL\gitsources\project>luajit.exe example/wrapper_run.lua sdl_one_window.lua sdl_one_window2.lua
Assertion failed!

Program: C:\LuaGL\gitsources\project\luajit.exe
File: C:\LuaGL\gitsources\anima\LuaJIT-ImGui\cimgui\imgui\backends\imgui_impl_sdl2.cpp, Line 398

Expression: io.BackendPlatformUserData == nullptr && "Already initialized a platform backend!"
```

so it is inited twice!!
because `local imgui_impl = nil` is always nil (being local but you could store imgui.imgui_impl to keep it)

Also: `loadfile("example/" .. arg[1], "t", copy(_G))()` is so strange because loadfile takes only one argument

**Comment by sonoro1234** [comment]
instead of `local imgui = loadfile("example/windowWrapperSdl.lua")()` perhaps `local imgui = require("windowWrapperSdl")` would help?

![Sin título](https://user-images.githubusercontent.com/1795930/220315824-2cc4874b-9b31-4d64-ac76-7336e8ae7bab.png)


[project.zip](https://github.com/sonoro1234/LuaJIT-ImGui/files/10792451/project.zip)

works for running sdlOneWindow.bat

**Comment by Sparebola** [comment]
> Also: `loadfile("example/" .. arg[1], "t", copy(_G))()` is so strange because loadfile takes only one argument

loadfile can take 3 arguments, you can check this by running loadfile.bat in [test.zip](https://github.com/sonoro1234/LuaJIT-ImGui/files/10793145/test.zip)
It's written about it [here](https://www.lua.org/manual/5.2/manual.html)

> instead of `local imgui = loadfile("example/windowWrapperSdl.lua")()` perhaps `local imgui = require("windowWrapperSdl")` would help?

I used loadfile instead of require to prevent caching "windowWrapperSdl" in package.loaded, because even specifying your global scope still doesn't solve the problem.
If you remember, in my RakSamp interpreter the scripts are completely isolated, which is exactly what I tried to do in the example on the regular luajit.
So there cannot be a global "imgui_impl".

**Comment by sonoro1234** [comment]
> I used loadfile instead of require to prevent caching "windowWrapperSdl" in package.loaded, because even specifying your global scope still doesn't solve the problem.

but the project.zip I sent you is working!!

> If you remember, in my RakSamp interpreter the scripts are completely isolated, which is exactly what I tried to do in the example on the regular luajit.

Perhaps you could pass it as an argument to a function that should be created by windowWrapperSdl.lua?
Or even keep it in the table created by copy(_G)?

**Comment by Sparebola** [comment]
> but the project.zip I sent you is working!!

It works because you changed the loadfile to require and thereby broke the file isolation. 

> Perhaps you could pass it as an argument to a function that should be created by windowWrapperSdl.lua?
> Or even keep it in the table created by copy(_G)?

Let's make one last push.
I am sending you a project with RakSamp, there imgui 1.82, because with imgui 1.89 the window hangs. All you need to do is to run "RakSAMP Lite.exe" and see the imgui window flashing.
[rak project.zip](https://github.com/sonoro1234/LuaJIT-ImGui/files/10795189/rak.project.zip)
There is no way you can break the isolation of the executables this way, unless you deliberately make a require. (see rule 2 and 3 below)


> I made three examples. You can quickly run through a bat file in the "run" folder:
> 
> 1. glfwMinimalDouble - launches two windows via glfw
> 2. sdlMinimalDouble - launches two windows via sdl
> 3. sdlOneWindow - runs a single window, in which draws two scripts at once
> 
> Errors:
> 
> * Method 1 and 2 - window freeze
> * Method  3 - blinking imgui
> 
> LuaJIT and binary files are taken from anima release [project.zip](https://github.com/sonoro1234/LuaJIT-ImGui/files/10786916/project.zip)

If you don't want to run a third-party exe, I suggest you take apart my first example. But be sure to follow the rules in order not to break the isolation: 
1. Do not change the files: sdl_one_window.lua, sdl_one_window2.lua and wrapper_run.lua. You can change only: windowWrapperSdl.lua and sdl libraries.
2. windowWrapperSdl.lua must not interact in any way with sdl_one_window.lua, sdl_one_window2.lua and wrapper_run.lua. These are independent libraries. (without require and load)
3. There can be more than two executable files (sdl_one_window[0-...].lua)
All these rules are needed to make RakSamp work again. That way you can really help me.

If you can't eliminate the blinking of windows, you can close the issue

**Comment by sonoro1234** [comment]
to avoid initing implementation twice, you need some kind of memory about it.
Is it ok to keep variables `imgui_impl` `window` and `glcontext` as fields of imgui table?

**Comment by Sparebola** [comment]
There is no way to store it, because the imgui table is different for each script. Window and glcontext can be obtained through ffi (there is an implementation), but imgui_impl, I do not know.

**Comment by sonoro1234** [comment]
using `print("thread",ffi.C.GetCurrentThread(),ffi.C.GetCurrentProcess(),_G)` in windowWrapperSdl.lua shows same thread, same process but different _G which I suppose to mean different lua_States. They should be able to communicate each other. RakSamp should provide any mechanism for that. If this is not the case LuaLanes or similar should be used.

**Comment by sonoro1234** [comment]
>but imgui_impl, I do not know.

You can get the imgui context with GetCurrentContext.

With two windows the main problem is not only imgui but also sdl: Having two windows each one in an isolated lua_state makes sdl events to be handled in two disconected event loops mixing events from both windows.

One window with two imgui contexts runs the sld event loop twice which also mix events.

Your best bet would be to have each lua script running in a different process (if possible with RakSamp)

**Comment by sonoro1234** [comment]
The best solution would be to have only one script with imgui_implementation performing the window and imgui draw loop.
The other scripts just provide imgui snippets to be executed between `imgui_impl:NewFrame()` and `imgui_impl:Render()` in the first script. (In case you can use RakSamp and Tasking.wait that way)
