### ISSUE TITLE
Typo in CMakeLists.txt

### ISSUE THREAD

**Issue by Simon-L** [sonoro1234/LuaJIT-ImGui#34]
First, thank you for your excellent work! I've started using these bindings for writing quick GUI apps on a handheld Linux device, it's very handy to have.

I just wanted to report a tiny typo in CMakeLists.txt, `BAKENDS_FOLDER` should obviously be `BACKENDS_FOLDER`.

Here's a patch:
[patch.txt](https://github.com/sonoro1234/LuaJIT-ImGui/files/11652639/patch.txt)

**Comment by sonoro1234** [comment]
Just curious: what are you using for the sdl glfw and opengl backends?

**Comment by Simon-L** [comment]
> Just curious: what are you using for the sdl glfw and opengl backends?

What do you mean by backend? I'm building for [JELOS](https://github.com/JustEnoughLinuxOS/distribution) so I have to use a specific toolchain with a sysroot containing all the dependencies so the SDL and GL backends are the versions already built by the toolchain with the shared objects and dev headers available in the sysroot. Thankfully, the target systems rely on SDL already so no extra dependencies was needed!

**Comment by sonoro1234** [comment]
done
