### ISSUE TITLE
Freeze during initialization

### ISSUE THREAD

**Issue by vadersug5** [sonoro1234/LuaJIT-ImGui#35]
Good afternoon. I build for Windows x64. For some reason, my application freezes whenever `Imgui_Impl_glfw_opengl3` is called. Could you please  tell me if there is a way to fix this? Thank you very much

**Comment by sonoro1234** [comment]
Lack of information.
Which glfw are you using?

**Comment by vadersug5** [comment]
glfw3. Downloaded from here: https://www.glfw.org/download

**Comment by sonoro1234** [comment]
Did you tried examples folder?. You need glfw LuaJIT binding for that.

**Comment by vadersug5** [comment]
Yes, I did. It works if I grab everything from releases. However, if I'm not mistaken, it is all built for Windows x32, so I had to compile it myself.
Yep. I call GLFW functions through ffi. Also, I forgot to add that it stops working regardless of whether I create OpenGL context or not

**Comment by sonoro1234** [comment]
Just updated LuaJIT-ImGui and anima to use imgui 1.89.6 docking. Could build anima with mingw for 32 and 64 bits and run example without problems

Also with msvc 2022 for 64bits
