### ISSUE TITLE
I have absolutely no idea how to build this.

### ISSUE THREAD

**Issue by bitceil** [sonoro1234/LuaJIT-ImGui#38]
The title says it all, i dont really have any experience in cmake and i find it difficult to build.
Can you please add a new release or create a new release every time a new imgui version rolls out?

Much appreciated.

**Comment by sonoro1234** [comment]
https://github.com/sonoro1234/LuaJIT-ImGui?tab=readme-ov-file#compiling

As said above, the easiest way is building anima
