### ISSUE TITLE
click does not work?

### ISSUE THREAD

**Issue by Corenale** [sonoro1234/LuaJIT-ImGui#39]
how do i compile this project as x64 dll?
i tried to do that and nothing renders for me
![image](https://github.com/user-attachments/assets/b4dfe518-b24a-4255-b3a7-5521938820e6)

**Comment by Corenale** [comment]
lua code used:
```lua
local ffi = require "ffi"
local lj_glfw = require"glfw"
local gllib = require"gl"
gllib.set_loader(lj_glfw)
local gl, glc, glu, glext = gllib.libraries()
local ig = require"imgui.glfw"

-- lj_glfw.setErrorCallback(function(error,description)
    -- print("GLFW error:",error,ffi.string(description or ""));
-- end)

lj_glfw.init()
local window = lj_glfw.Window(700,500)
window:makeContextCurrent() 

--choose implementation
--local ig_impl = ig.ImplGlfwGL3() --multicontext
local ig_impl = ig.Imgui_Impl_glfw_opengl3() --standard imgui opengl3 example
--local ig_impl = ig.Imgui_Impl_glfw_opengl2() --standard imgui opengl2 example

local igio = ig.GetIO()
igio.ConfigFlags = ig.lib.ImGuiConfigFlags_NavEnableKeyboard + igio.ConfigFlags


ig_impl:Init(window, true)

local showdemo = ffi.new("bool[1]",false)
while not window:shouldClose() do

    lj_glfw.pollEvents()
    
    gl.glClear(glc.GL_COLOR_BUFFER_BIT)
    
    ig_impl:NewFrame()
    
    if ig.Button"Hello" then
        print"Hello World!!"
    end
    ig.ShowDemoWindow(showdemo)
    
    ig_impl:Render()
    
    window:swapBuffers()                    
end

ig_impl:destroy()
window:destroy()
lj_glfw.terminate()
```

**Comment by sonoro1234** [comment]
> i tried to do that and nothing renders for me

So you managed to compile (as it should be also for x64) . You also have a LuaJIT installation with glfw and etc... as can be deduced for the lack of error messages. It can be runned but nothing is rendered. It could be a GPU issue with opengl, perhaps a double GPU as found in many laptops where you should assign the best GPU for running LuaJIT.

You should check with Dear imgui example for glfw and opengl and report. https://github.com/ocornut/imgui/tree/master/examples/example_glfw_opengl3

**Comment by Corenale** [comment]
![image](https://github.com/user-attachments/assets/379481cc-8fbd-4823-b55a-79f66c313425)
but your dll from releases works fine (https://github.com/sonoro1234/LuaJIT-ImGui/releases/tag/v1.62)
maybe I'm compiling it incorrectly?

**Comment by Corenale** [comment]
[cimgui_glfw.zip](https://github.com/user-attachments/files/16752571/cimgui_glfw.zip)
i dont know c++ :(
i just want to use this library with 64 bit luajit

**Comment by sonoro1234** [comment]
You can compile c++ dear imgui without knowing c++
Have you checked GPU?

**Comment by Corenale** [comment]
![image](https://github.com/user-attachments/assets/92f886d0-e3f9-40f8-82c9-c17103f29a32)
i just used cmake on the folder with luajit-imgui, it gave me cimgui.sln, then i added the paths to glfw3 and compiled it
maybe you can compile it for me?
![image](https://github.com/user-attachments/assets/31348d10-7aa2-4b86-92bd-28c66c2972e4)
I only have one gtx 1060 3gb

**Comment by Corenale** [comment]
sorry for wasting your time, my problem.
should have used the code from examples/minimal_main_viewport.lua
and everything works
thanks for answering, I'm just stupid :)

this code fixes my issue:
```lua
local igio = ig.GetIO()
ig.GetIO().ConfigFlags = ig.lib.ImGuiConfigFlags_ViewportsEnable + igio.ConfigFlags
```

```lua
window:makeContextCurrent() 
if bit.band(igio.ConfigFlags , ig.lib.ImGuiConfigFlags_ViewportsEnable) ~= 0 then
  ig.UpdatePlatformWindows();
  ig.RenderPlatformWindowsDefault();
end
window:makeContextCurrent() 
```

![image](https://github.com/user-attachments/assets/aa400e9d-1574-4ad7-b616-c189fceff783)

**Comment by Corenale** [comment]
new problem
I can't click on imgui

**Comment by sonoro1234** [comment]
examples/minimal_main.lua should also works but without docking and viewport
click should work also.

You could check with `	print(ig.GetMousePos())`

**Comment by Corenale** [comment]
I made callbacks, now it sees clicks, but it clicks without any idea where
![image](https://github.com/user-attachments/assets/29831693-7920-4253-8174-351fa069ab34)
![image](https://github.com/user-attachments/assets/033faf63-6234-4148-b587-e1649c47cd84)

**Comment by sonoro1234** [comment]
You dont need to set callbacks. Is mouse pos changing?

**Comment by Corenale** [comment]
![image](https://github.com/user-attachments/assets/c6690bc4-9453-4bf5-8bac-69aa0ba5abe3)
yes, but after clicking imgui window lost focus

**Comment by sonoro1234** [comment]
clicking where? could you send video?

**Comment by Corenale** [comment]
https://github.com/user-attachments/assets/7a00a1d1-3ca2-4257-9cb4-6dfaebe06223

**Comment by sonoro1234** [comment]
I cant see it. Better with a GIF recorder.

**Comment by Corenale** [comment]
is this better?
https://www.youtube.com/watch?v=8YKAR0zQpjM

**Comment by sonoro1234** [comment]
Why is Button so big?
Did you run original example?
Try do delete imgui.ini before running

**Comment by Corenale** [comment]
black screen and clicks don't work
deleting imgui.ini did not help

![image](https://github.com/user-attachments/assets/cad939a7-ab5f-4581-8a10-460c1c1f2854)
to hit the button when the window is black

**Comment by sonoro1234** [comment]
Try original example. When clicking button consolé prints Hello.

May be update glfw?

**Comment by Corenale** [comment]
![image](https://github.com/user-attachments/assets/57f2aed6-47a9-485c-8bbe-fb8f0c42b999)
i'm using last glfw 3.4

![image](https://github.com/user-attachments/assets/73fb49d6-52a5-4f70-9d5f-db3fe590ee1a)
![image](https://github.com/user-attachments/assets/194d167d-aa05-4e74-b10e-ca6568ae16a2)

**Comment by sonoro1234** [comment]
Nothing should happen clicking in black screen.
I dont know what else suggest. Perhaps you could try building anima which has all the dependencies and then running minimal_main_viewport.lua example

**Comment by Corenale** [comment]
![image](https://github.com/user-attachments/assets/babe1ebe-89ac-4c36-97d0-af6337f67c51)
igio.MouseDrawCursor = true
ig.GetForegroundDrawList():AddCircle(igio.MouseClickedPos[0],5,-1,42,2)
it sees the cursor and clicks, but still can't click on the imgui window
it feels like it's clicking through the imgui window

**Comment by sonoro1234** [comment]
> it feels like it's clicking through the imgui window

I am not sure to understand. 
Perhaps if you play with demo window you can show the bad behaviour.

**Comment by Corenale** [comment]
> Perhaps if you play with demo window you can show the bad behaviour.

it has the same issue

**Comment by sonoro1234** [comment]
x64 anima LuaJIT imgui compiled with NMake msvc

![GIF111](https://github.com/user-attachments/assets/33b6e401-ae96-45eb-8f4f-f38ca24eec84)

**Comment by Corenale** [comment]
> x64 anima LuaJIT imgui compiled with NMake msvc
> 
> ![GIF111](https://private-user-images.githubusercontent.com/1795930/362227970-33b6e401-ae96-45eb-8f4f-f38ca24eec84.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4MzkwMjgsIm5iZiI6MTcyNDgzODcyOCwicGF0aCI6Ii8xNzk1OTMwLzM2MjIyNzk3MC0zM2I2ZTQwMS1hZTk2LTQ1ZWItOGY0Zi1mMzhjYTI0ZWVjODQuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjhUMDk1MjA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODYyMWZiYzdlOWRjYWQ2MTMzNDIwMmUzNGM5MzczZDQ2OTc5ZjYzMjAxMzhiYjM1ZGZlNTk2ODU0MTVjMDg3NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.aNPE6zpxBy1ijx5ZQsBX49ywWFKG2_-qyIT6Q7QAqDc) [ ![GIF111](https://private-user-images.githubusercontent.com/1795930/362227970-33b6e401-ae96-45eb-8f4f-f38ca24eec84.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4MzkwMjgsIm5iZiI6MTcyNDgzODcyOCwicGF0aCI6Ii8xNzk1OTMwLzM2MjIyNzk3MC0zM2I2ZTQwMS1hZTk2LTQ1ZWItOGY0Zi1mMzhjYTI0ZWVjODQuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjhUMDk1MjA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODYyMWZiYzdlOWRjYWQ2MTMzNDIwMmUzNGM5MzczZDQ2OTc5ZjYzMjAxMzhiYjM1ZGZlNTk2ODU0MTVjMDg3NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.aNPE6zpxBy1ijx5ZQsBX49ywWFKG2_-qyIT6Q7QAqDc) ](https://private-user-images.githubusercontent.com/1795930/362227970-33b6e401-ae96-45eb-8f4f-f38ca24eec84.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4MzkwMjgsIm5iZiI6MTcyNDgzODcyOCwicGF0aCI6Ii8xNzk1OTMwLzM2MjIyNzk3MC0zM2I2ZTQwMS1hZTk2LTQ1ZWItOGY0Zi1mMzhjYTI0ZWVjODQuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjhUMDk1MjA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODYyMWZiYzdlOWRjYWQ2MTMzNDIwMmUzNGM5MzczZDQ2OTc5ZjYzMjAxMzhiYjM1ZGZlNTk2ODU0MTVjMDg3NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.aNPE6zpxBy1ijx5ZQsBX49ywWFKG2_-qyIT6Q7QAqDc) [ ](https://private-user-images.githubusercontent.com/1795930/362227970-33b6e401-ae96-45eb-8f4f-f38ca24eec84.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4MzkwMjgsIm5iZiI6MTcyNDgzODcyOCwicGF0aCI6Ii8xNzk1OTMwLzM2MjIyNzk3MC0zM2I2ZTQwMS1hZTk2LTQ1ZWItOGY0Zi1mMzhjYTI0ZWVjODQuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjhUMDk1MjA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODYyMWZiYzdlOWRjYWQ2MTMzNDIwMmUzNGM5MzczZDQ2OTc5ZjYzMjAxMzhiYjM1ZGZlNTk2ODU0MTVjMDg3NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.aNPE6zpxBy1ijx5ZQsBX49ywWFKG2_-qyIT6Q7QAqDc)

omg can you give it to me?

**Comment by sonoro1234** [comment]
ig.ShowDemoWindow is the function, you can use it in 
examples/minimal_main_viewport.lua and check what happens.

https://github.com/sonoro1234/anima is the repo in case you want to build all dependencies

**Comment by Corenale** [comment]
compiling imgui from anima solves the problem
