### ISSUE TITLE
create texture?

### ISSUE THREAD

**Issue by Corenale** [sonoro1234/LuaJIT-ImGui#40]
I want to create a texture from a picture and use it in ig.Image but I don't know how. Can you help me with this? I use glfw if that's important

**Comment by sonoro1234** [comment]
https://github.com/ocornut/imgui/wiki/Image-Loading-and-Displaying-Examples#example-for-opengl-users is the imgui guide. You should look at opengl example, glfw is not relevant. For loading the image it uses stb but you can use any other library.

**Comment by Corenale** [comment]
![image](https://github.com/user-attachments/assets/875d6c3f-7844-4b36-87c5-22fd1d88584b)
Which one, for example?

**Comment by sonoro1234** [comment]
https://github.com/libvips/lua-vips
https://github.com/sonoro1234/mirror-im/tree/bd34a8cdaac62eac99f5fa1de7510bbe18aaf7af
https://github.com/stetre/moonimage
https://www.tecgraf.puc-rio.br/iup/en/iupim.html
https://github.com/thenumbernine/lua-image

or any other image loading library which can be loaded from LuaJIT ffi

The second one is used in anima as a ffi interface to iup im

**Comment by Corenale** [comment]
![image](https://github.com/user-attachments/assets/89151e98-9898-487b-a5c5-01c8dafa2181)
with this code i get a black image, what am i doing wrong?

**Comment by sonoro1234** [comment]
Witdh and height are 512? format is GL_RGBA? datatype is GL_UNSIGNED_BYTE?
Did you use ig.Image? im.FileImageLoad did return an error? Is opengl inited? (ImGui_ImplOpenGL3_Init(glsl_version); is executed before)

My (quite dirty) code to load image is found in https://github.com/sonoro1234/anima/blob/528cb52f2d4a6e4c407070c823c816433be3902b/anima/textures.lua#L447

**Comment by Corenale** [comment]
![image](https://github.com/user-attachments/assets/e17a936e-bed6-41ec-91c0-0c2913529fd4)
doesnt work anyway
im.FileImageLoad works fine
i'm use ig.Image

**Comment by Corenale** [comment]
![image](https://github.com/user-attachments/assets/9ffce52f-0b74-49f4-98d4-ea293c5c973e)
doesnt work anyway
im.FileImageLoad works fine
i'm use ig.Image

**Comment by sonoro1234** [comment]
If you wish my help you should post the whole script code here as in:

```Lua
function doit(a,b)
  print(a,b)
end

doit(1,2)
```
dont send images of the code please.

But as the code seems to come from `minimal_main_viewport.lua` I can guess that you should put your code after 
```Lua
ig_impl:Init(window, true)
```
where opengl is initiated

**Comment by Corenale** [comment]
```lua
local ffi = require "ffi"
jit.off(true,true)
local lj_glfw = require"glfw"
local gllib = require"gl"
gllib.set_loader(lj_glfw)
local gl, glc, glu, glext = gllib.libraries()
local ig = require"imgui.glfw"
local imgui = ig


lj_glfw.init()


local window = lj_glfw.Window(1000,1000, cheatWindowName)

window:makeContextCurrent()

local ig_impl = ig.Imgui_Impl_glfw_opengl3() --standard imgui opengl3 example



local igio = ig.GetIO()
local style = imgui.GetStyle()
local colors = style.Colors
igio.WantCaptureMouse = false
igio.WantSaveIniSettings = false
imgui.GetIO().IniFilename = nil
igio.ConfigFlags = ig.lib.ImGuiConfigFlags_NavEnableKeyboard + igio.ConfigFlags  -- Enable Keyboard Controls


ig_impl:Init(window, true)

local im = require"imffi"
local img = im.FileImageLoad("C:\\image.png")
local image_data, glformat = img:GetOpenGLData()
local datatype = img:DataType()
image_texture = ffi.new("GLuint[1]")
gl.glGenTextures(1, image_texture);
gl.glBindTexture(glc.GL_TEXTURE_2D, image_texture[0]);

gl.glPixelStorei(glc.GL_UNPACK_ALIGNMENT, 1)
gl.glTexImage2D(glc.GL_TEXTURE_2D, 0, glformat[0], 512, 512, 0, glformat[0], datatype, image_data);

while true do

	lj_glfw.pollEvents()
	
	gl.glClear(glc.GL_COLOR_BUFFER_BIT)
	
	ig_impl:NewFrame()

			imgui.SetNextWindowSize(imgui.ImVec2(800, 800))
			imgui.Begin("1")
				imgui.GetWindowDrawList():AddImage(ffi.cast("void*", ffi.cast("uintptr_t", image_texture)), imgui.ImVec2(0, 0), imgui.ImVec2(512, 512), imgui.ImVec2(0,0), imgui.ImVec2(1,1), -1)
			imgui.End()

    ig_impl:Render()
    window:swapBuffers()
end

ig_impl:destroy()
window:destroy()
lj_glfw.terminate()
```
image.png:
https://github.com/user-attachments/assets/61052104-d252-4296-b99f-514d64e487b6

**Comment by Corenale** [comment]
> ```lua
> local ffi = require "ffi"
> jit.off(true,true)
> local lj_glfw = require"glfw"
> local gllib = require"gl"
> gllib.set_loader(lj_glfw)
> local gl, glc, glu, glext = gllib.libraries()
> local ig = require"imgui.glfw"
> local imgui = ig
> 
> 
> lj_glfw.init()
> 
> 
> local window = lj_glfw.Window(1000,1000, cheatWindowName)
> 
> window:makeContextCurrent()
> 
> local ig_impl = ig.Imgui_Impl_glfw_opengl3() --standard imgui opengl3 example
> 
> 
> 
> local igio = ig.GetIO()
> local style = imgui.GetStyle()
> local colors = style.Colors
> igio.WantCaptureMouse = false
> igio.WantSaveIniSettings = false
> imgui.GetIO().IniFilename = nil
> igio.ConfigFlags = ig.lib.ImGuiConfigFlags_NavEnableKeyboard + igio.ConfigFlags  -- Enable Keyboard Controls
> 
> 
> ig_impl:Init(window, true)
> 
> local im = require"imffi"
> local img = im.FileImageLoad("C:\\image.png")
> local image_data, glformat = img:GetOpenGLData()
> local datatype = img:DataType()
> image_texture = ffi.new("GLuint[1]")
> gl.glGenTextures(1, image_texture);
> gl.glBindTexture(glc.GL_TEXTURE_2D, image_texture[0]);
> 
> gl.glPixelStorei(glc.GL_UNPACK_ALIGNMENT, 1)
> gl.glTexImage2D(glc.GL_TEXTURE_2D, 0, glformat[0], 512, 512, 0, glformat[0], datatype, image_data);
> 
> while true do
> 
> 	lj_glfw.pollEvents()
> 	
> 	gl.glClear(glc.GL_COLOR_BUFFER_BIT)
> 	
> 	ig_impl:NewFrame()
> 
> 			imgui.SetNextWindowSize(imgui.ImVec2(800, 800))
> 			imgui.Begin("1")
> 				imgui.GetWindowDrawList():AddImage(ffi.cast("void*", ffi.cast("uintptr_t", image_texture)), imgui.ImVec2(0, 0), imgui.ImVec2(512, 512), imgui.ImVec2(0,0), imgui.ImVec2(1,1), -1)
> 			imgui.End()
> 
>     ig_impl:Render()
>     window:swapBuffers()
> end
> 
> ig_impl:destroy()
> window:destroy()
> lj_glfw.terminate()
> ```
> 
> image.png: https://github.com/user-attachments/assets/61052104-d252-4296-b99f-514d64e487b6

doesn't work

**Comment by dinau** [comment]
Hi @Corenale
Would you try [this example project](https://github.com/dinau/luajitImGui) ? 
[Load image function](https://github.com/dinau/luajitImGui/blob/main/bin/lua/mylib/loadImage.lua) used stb_image is here.

**Comment by Corenale** [comment]
> Hi @Corenale Would you try [this example project](https://github.com/dinau/luajitImGui) ? [Load image function](https://github.com/dinau/luajitImGui/blob/main/bin/lua/mylib/loadImage.lua) used stb_image is here.

i need a 64 bit version of dll

**Comment by dinau** [comment]
> i need a 64 bit version of dll

[Uploaded 64bit version](https://github.com/dinau/luajitImGui?tab=readme-ov-file#download-zip-binary)

**Comment by sonoro1234** [comment]
This is working:

```Lua
local ffi = require "ffi"
jit.off(true,true)
local lj_glfw = require"glfw"
local gllib = require"gl"
gllib.set_loader(lj_glfw)
local gl, glc, glu, glext = gllib.libraries()
local ig = require"imgui.glfw"
local imgui = ig


lj_glfw.init()


local window = lj_glfw.Window(1000,1000, cheatWindowName)

window:makeContextCurrent()

local ig_impl = ig.Imgui_Impl_glfw_opengl3() --standard imgui opengl3 example



local igio = ig.GetIO()
local style = imgui.GetStyle()
local colors = style.Colors
igio.WantCaptureMouse = false
igio.WantSaveIniSettings = false
imgui.GetIO().IniFilename = nil
igio.ConfigFlags = ig.lib.ImGuiConfigFlags_NavEnableKeyboard + igio.ConfigFlags  -- Enable Keyboard Controls


ig_impl:Init(window, true)


local im = require"imffi"
local fileName = "image.png"
local img,err = im.FileImageLoad(fileName)
		if (img==nil) then
			print ("Unnable to open the file:", fileName)
			error(im.ErrorStr(err))
		end
local w,h = img:Width(), img:Height()
local image_data, glformat = img:GetOpenGLData()
assert(img:DataType()==im.BYTE,im.DataTypeName(img:DataType()))
local datatype = glc.GL_UNSIGNED_BYTE
local image_texture = ffi.new("GLuint[1]")
gl.glGenTextures(1, image_texture);
gl.glBindTexture(glc.GL_TEXTURE_2D, image_texture[0]);
gl.glTexParameteri(glc.GL_TEXTURE_2D,glc.GL_TEXTURE_MIN_FILTER,glc.GL_LINEAR)
gl.glTexParameteri(glc.GL_TEXTURE_2D,glc.GL_TEXTURE_MAG_FILTER,glc.GL_LINEAR)
gl.glPixelStorei(glc.GL_UNPACK_ROW_LENGTH, 0);
gl.glTexImage2D(glc.GL_TEXTURE_2D, 0, glc.GL_RGBA, w, h, 0, glformat, datatype, image_data);

while not window:shouldClose() do
	lj_glfw.pollEvents()
	
	gl.glClear(glc.GL_COLOR_BUFFER_BIT)
	
	ig_impl:NewFrame()

			imgui.SetNextWindowSize(imgui.ImVec2(800, 800))
			imgui.Begin("1")
				imgui.Image(ffi.cast("void*",image_texture[0]),imgui.ImVec2(w,h),imgui.ImVec2(1,1), imgui.ImVec2(0,0))
				--imgui.GetWindowDrawList():AddImage(ffi.cast("void*", ffi.cast("uintptr_t", image_texture[0])), imgui.ImVec2(0, 0), imgui.ImVec2(512, 512), imgui.ImVec2(0,0), imgui.ImVec2(1,1), -1)
			imgui.End()

    ig_impl:Render()
    window:swapBuffers()
end

ig_impl:destroy()
window:destroy()
lj_glfw.terminate()
```

**Comment by Corenale** [comment]
> > i need a 64 bit version of dll
> 
> [Uploaded 64bit version](https://github.com/dinau/luajitImGui?tab=readme-ov-file#download-zip-binary)

thank you, now i can load pics from memory



> This is working:
> 
> ```lua
> local ffi = require "ffi"
> jit.off(true,true)
> local lj_glfw = require"glfw"
> local gllib = require"gl"
> gllib.set_loader(lj_glfw)
> local gl, glc, glu, glext = gllib.libraries()
> local ig = require"imgui.glfw"
> local imgui = ig
> 
> 
> lj_glfw.init()
> 
> 
> local window = lj_glfw.Window(1000,1000, cheatWindowName)
> 
> window:makeContextCurrent()
> 
> local ig_impl = ig.Imgui_Impl_glfw_opengl3() --standard imgui opengl3 example
> 
> 
> 
> local igio = ig.GetIO()
> local style = imgui.GetStyle()
> local colors = style.Colors
> igio.WantCaptureMouse = false
> igio.WantSaveIniSettings = false
> imgui.GetIO().IniFilename = nil
> igio.ConfigFlags = ig.lib.ImGuiConfigFlags_NavEnableKeyboard + igio.ConfigFlags  -- Enable Keyboard Controls
> 
> 
> ig_impl:Init(window, true)
> 
> 
> local im = require"imffi"
> local fileName = "image.png"
> local img,err = im.FileImageLoad(fileName)
> 		if (img==nil) then
> 			print ("Unnable to open the file:", fileName)
> 			error(im.ErrorStr(err))
> 		end
> local w,h = img:Width(), img:Height()
> local image_data, glformat = img:GetOpenGLData()
> assert(img:DataType()==im.BYTE,im.DataTypeName(img:DataType()))
> local datatype = glc.GL_UNSIGNED_BYTE
> local image_texture = ffi.new("GLuint[1]")
> gl.glGenTextures(1, image_texture);
> gl.glBindTexture(glc.GL_TEXTURE_2D, image_texture[0]);
> gl.glTexParameteri(glc.GL_TEXTURE_2D,glc.GL_TEXTURE_MIN_FILTER,glc.GL_LINEAR)
> gl.glTexParameteri(glc.GL_TEXTURE_2D,glc.GL_TEXTURE_MAG_FILTER,glc.GL_LINEAR)
> gl.glPixelStorei(glc.GL_UNPACK_ROW_LENGTH, 0);
> gl.glTexImage2D(glc.GL_TEXTURE_2D, 0, glc.GL_RGBA, w, h, 0, glformat, datatype, image_data);
> 
> while not window:shouldClose() do
> 	lj_glfw.pollEvents()
> 	
> 	gl.glClear(glc.GL_COLOR_BUFFER_BIT)
> 	
> 	ig_impl:NewFrame()
> 
> 			imgui.SetNextWindowSize(imgui.ImVec2(800, 800))
> 			imgui.Begin("1")
> 				imgui.Image(ffi.cast("void*",image_texture[0]),imgui.ImVec2(w,h),imgui.ImVec2(1,1), imgui.ImVec2(0,0))
> 				--imgui.GetWindowDrawList():AddImage(ffi.cast("void*", ffi.cast("uintptr_t", image_texture[0])), imgui.ImVec2(0, 0), imgui.ImVec2(512, 512), imgui.ImVec2(0,0), imgui.ImVec2(1,1), -1)
> 			imgui.End()
> 
>     ig_impl:Render()
>     window:swapBuffers()
> end
> 
> ig_impl:destroy()
> window:destroy()
> lj_glfw.terminate()
> ```

thank you too, now i can load pics :)
